behaviors:
  HiderBehavior:
    trainer_type: poca
    hyperparameters:
      batch_size: 32000
      buffer_size: 960000
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000000
    time_horizon: 64
    summary_freq: 150000
  SeekerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32000
      buffer_size: 480000
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000000
    time_horizon: 64
    summary_freq: 150000